#!/usr/bin/php -q
<?php
require_once('base');

if (count($argv)<2) dead('Need Param LaneID/DateNum');
if (count(explode('/',$argv[1],2))!=2) dead('Incomplete Param');

list($sLN, $sDT) = explode('/',$argv[1],2);
$iDT = (int)$sDT; if ($iDT<140101 || $iDT>291212) $iDT = (int)substr(date('Ymd'),2);

$sDT = sprintf("%06d", $iDT);
$fileLogName = LOG_PATH.'/'.$sLN.'/ALL_20'.substr($sDT,0,2).'-'.substr($sDT,2,2).'-'.substr($sDT,4,2).'.log.gz';
if (!file_exists($fileLogName)) 
	$fileLogName = LOG_PATH.'/'.$sLN.'/20'.substr($sDT,0,2).'-'.substr($sDT,2,2).'-'.substr($sDT,4,2).'.log.gz';
if (!file_exists($fileLogName)) dead('File Log NOT FOUND!!: '.$fileLogName);

$fp = gzopen($fileLogName, 'r');
if (false===$fp) dead('Cannot Open log file');
$countLine = 0;
while (!gzeof($fp)) {
	$line = gzgets($fp);
	$countLine++;
	$dat1 = substr(rtrim($line),2);
	
	print (rtrim($line).PHP_EOL);
}
gzclose($fp);

//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
//----------------------------------------------------------------------------

?>
