#!/usr/bin/php -q
<?php
require_once('base');

if (count($argv)<2) dead('Need Param LaneId/DateNum/HourNum');
if (count(explode('/',$argv[1],3))!=3) dead('Incomplete Param');

list($sLN, $sDT, $sHR) = explode('/',$argv[1],3);
$iDT = (int)$sDT; if ($iDT<140101 || $iDT>291212) $iDT = (int)substr(date('Ymd'),2);
if ($sHR=='') $sHR=date('H');
$iHR = (int)$sHR; if ($iHR>24) $iHR = (int)date('H');

#echo 'sLN=',$sLN, ' sDT=', $sDT, ' sHR=', $sHR, PHP_EOL;
#echo 'iLN=',$iLN, ' iDT=',$iDT, ' iHR=',$iHR, PHP_EOL;

$sDT = sprintf("%06d", $iDT);
$fileLogName = LOG_PATH.'/'.$sLN.'/ALL_20'.substr($sDT,0,2).'-'.substr($sDT,2,2).'-'.substr($sDT,4,2).'.log.gz';
if (!file_exists($fileLogName)) $fileLogName = LOG_PATH.'/'.$sLN.'/20'.substr($sDT,0,2).'-'.substr($sDT,2,2).'-'.substr($sDT,4,2).'.log.gz';
if (!file_exists($fileLogName)) dead('File Log NOT FOUND!!');
$fp = gzopen($fileLogName, 'r');
if (false===$fp) dead('Cannot Open log file');
$countLine = 0;
$sHour = sprintf("%02d", $iHR);
$isFound = false;
while (!gzeof($fp)) {
	$line = gzgets($fp);
	$countLine++;
	$dat1 = substr(rtrim($line),2);
	if (! $isFound) {
		if (preg_match('/^[A-Z]\[\d{6}\:\d{6}]/', $line)) {
			if ($sHour != substr($dat1,0,2)) continue;
			$isFound = true;	// Found correct Hour
		}
	}
	else {
		if (preg_match('/^[A-Z]\[\d{6}\:\d{6}]/', $line)) {
			if ($sHour != substr($dat1,0,2)) {
				break;
			}
		}
	}
	
	print (rtrim($line).PHP_EOL);
//	if ($countLine > 100) break;
}
gzclose($fp);

//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
//----------------------------------------------------------------------------

?>
