#!/usr/bin/php -q
<?php

define('T', 'T');	// All Transaction
define('Q', 'Q');	// Clear Q
define('B', 'B');	// Override Barrier
define('P', 'P');	// Open by Portable
define('E', 'E');	// Empty Money
define('N', 'N');	// NO TAG
define('TAB',"\t");

$stat = array();
for ($i=0; $i<24; $i++) $stat[sprintf("%02d",$i)] = array(T=>0, Q=>0,N=>0,B=>0,P=>0,E=>0);

while ($line = fgets(STDIN)) {
	$hr = substr($line, 2, 2);		// Hour number

	if ((strpos($line, 'D[')!==false)&&(strpos($line, 'AVC Car VCLASS')!==false)) { $stat[$hr][T] += 1;	continue; }
	if (strpos($line, 'SetOpenBySlave(PassageCode=')!==false) { $stat[$hr][P] += 1; continue; }
	if (strpos($line, 'BalanceMinRequire')!==false) { $stat[$hr][E] += 1; continue; }
	if (strpos($line, 'LOGIC_ERROR.NO_TAG')!==false) { $stat[$hr][N] += 1; continue; }

	if (strpos($line, 'Begin CLEAN-QUEUE')!==false) { $stat[$hr][Q] += 1; continue; }
}

echo str_repeat('-', 79), PHP_EOL;
echo 'HR', TAB, 
	sprintf("%4s",T), TAB, 	// Total Transaction
	sprintf("%4s",Q), TAB, 	// Clear Queue
//	sprintf("%4s",A), TAB,
	sprintf("%4s",N), TAB,	// No TAG
	sprintf("%4s",E), TAB,	// Empty MOney
	sprintf("%4s",P),		// Open by Portable
	PHP_EOL;
echo str_repeat('-', 79), PHP_EOL;

$sum_t = 0;
$sum_q = 0;
$sum_n = 0;
$sum_b = 0;
$sum_e = 0;
$sum_p = 0;

foreach ($stat as $hr=>$value) {
	$t = (int)$value[T];
	$q = (int)$value[Q];
	$n = (int)$value[N];
	$b = (int)$value[B];
	$e = (int)$value[E];
	$p = (int)$value[P];

	$sum_t += $t;
	$sum_q += $q;
	$sum_n += $n;
	$sum_b += $b;
	$sum_e += $e;
	$sum_p += $p;

	echo $hr, TAB, 
	(($t>0)?(sprintf("%4d", $t)):(' ')), TAB,
	(($q>0)?(sprintf("%4d", $q)):(' ')), TAB,
	(($n>0)?(sprintf("%4d", $n)):(' ')), TAB,
//	(($b>0)?(sprintf("%4d", $b)):(' ')), TAB,
	(($e>0)?(sprintf("%4d", $e)):(' ')), TAB,
	(($p>0)?(sprintf("%4d", $p)):(' ')),
	PHP_EOL;
}

echo str_repeat('-', 79), PHP_EOL;
echo 'ALL', TAB, 
	sprintf("%4d", $sum_t), TAB, 
	sprintf("%4d", $sum_q), TAB, 
	sprintf("%4d", $sum_n), TAB,
//	sprintf("%4d", $sum_b), TAB,
	sprintf("%4d", $sum_e), TAB,
	sprintf("%4d", $sum_p),
	PHP_EOL;
echo str_repeat('-', 79), PHP_EOL;

//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
//----------------------------------------------------------------------------
?>
