#!/usr/bin/php -q
<?php
require_once('base');

if (count($argv)<2) dead('Need Param MinuteBegin/MinuteEnd');
if (count(explode('/',$argv[1],2))!=2) dead('Invalid Param MinuteBegin/MinuteEnd');
list($sMin1, $sMin2) = explode('/',$argv[1],2);
$iMin1 = (int)$sMin1; $iMin2 = (int)$sMin2;
if ($iMin1>$iMin2) dead('Invalid Minute Range');
if ($iMin1 < 0 || $iMin1 > 59 || $iMin2 < 0 || $iMin2 > 59) dead('Invalid Minute Value');
$M1 = sprintf("%02d", $iMin1);
$M2 = sprintf("%02d", $iMin2);
#echo 'M1=',$M1, ' M2=',$M2, PHP_EOL;

while ($line = fgets(STDIN)) {
	$MN = substr($line,4,2);
	if ($MN >= $M1 && $MN <= $M2) print($line);
}

?>
