#!/usr/bin/php -q
<?php
require_once('base');

if (count($argv)<2) dead('Need Param SecondBegin/SecondEnd');
if (count(explode('/',$argv[1],2))!=2) dead('Invalid Param SecondBegin/SecondEnd');
list($sSec1, $sSec2) = explode('/',$argv[1],2);
$iSec1 = (int)$sSec1; $iSec2 = (int)$sSec2;
if ($iSec1>$iSec2) dead('Invalid Minute Range');
if ($iSec1 < 0 || $iSec1 > 59 || $iSec2 < 0 || $iSec2 > 59) dead('Invalid Minute Value');
$S1 = sprintf("%02d", $iSec1);
$S2 = sprintf("%02d", $iSec2);
//echo 'S1=',$S1, ' S2=',$S2, PHP_EOL;

while ($line = fgets(STDIN)) {
	$SC = substr($line,6,2);
	if ($SC >= $S1 && $SC <= $S2) print($line);
}

?>
